# TATOA Internal Status Monitor
owner: TATOA-DEV
repo: status

sites:
  - name: BE Production
    url: https://be-prd.tatoaweb.com/actuator/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
  - name: BE Staging
    url: https://be-stg.tatoa-web-y.com/actuator/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
  - name: BE Development
    url: https://be-dev.tatoa-web-y.com/actuator/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

workflowSchedule:
  uptime: "*/15 * * * *"

status-website:
  name: TATOA Internal Status
  introTitle: TATOA 내부 시스템 상태
  introMessage: TATOA 백엔드 서비스의 실시간 가용성 모니터링.
